### ISSUE TITLE
Parsing FlyBy triggers

### ISSUE THREAD

**Issue by sapper-trle** [chreden/trview#616] opened 2020-01-02 02:56 UTC
FlyBy triggers have an additional uint16_t same as Camera. Except for those in title.tr4 of TRLE.

**Comment by chreden** [comment] 2020-01-02 10:12
Thanks, I already made an issue for this. I will add the detail about title.tr4 to it though.
Duplicate of #610

**Closed by chreden** 2020-01-02 10:12 UTC
